# Site
name: "khunemz"
title: "CHUTIPONG ROOBKLOM"
description: "A PERSONAL BLOG. BUILD FOR DEVELOPER's CRAFTSMANSHIP."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-46278016-1'
disqus: 'khunemz-github-io'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
# Page
url: "https://www.facebook.com/khunemz"
# Authors
authors:
  author0:
    name: chutipong.r
    avatar: 'assets/images/myAvatar.png'
    display_name: khunemz
    gravatar: 8117cccc37871d26746dac2ee3c5433e
    email: khunemz@gmail.com
    web: https://khunemz.github.io
    twitter: https://twitter.com/khun_emz
    description: "Author of khunemz.github.io, CEO CMR group"
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: khunemz@gmail.com
    web: https://khunemz.github.io
    twitter: https://twitter.com/khun_emz
    description: "John Doe"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
